version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emanage-next-frontend
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    restart: always
